### ISSUE TITLE
Redirect https://docs.silverstripe.org/en/current/ alias to latest stable release

### ISSUE THREAD

**Issue by chillu** [silverstripe/doc.silverstripe.org#119]
This used to work on docs, and is important particularly for long-running links which you don't want to change every time a new release is coming out - which is becoming more frequent with the adoption of semver.

**Comment by camfindlay** [comment]
Should be able to do a rewrite for this, if you go to just /en/ it will auto direct to stable so current could just redir to /en/ to take advantage of this.

**Comment by unclecheese** [comment]
Since this is now statically rendered, we can't compute the lastest version on the fly. We can do it from within the gatsby app, but doing the redirect client side is quite slow and it makes the TTFI quite latent.

Are we okay leaving this as a Netlify level redirect? See `netlify.toml`.

If not, please reopen and state your case.
