### ISSUE TITLE
Keep full path when switching between versions

### ISSUE THREAD

**Issue by chillu** [silverstripe/doc.silverstripe.org#120]
If I'm on `https://docs.silverstripe.org/en/3.2/developer_guides/model/`, and click `4.0`, I'd expect to get redirected to `https://docs.silverstripe.org/en/4.0/developer_guides/model/`. In fact, I'm redirected to `https://docs.silverstripe.org/en/4.0/`. Losing the context makes it harder for early adopters, and seems like an easy fix in the codebase (it used to work about a year ago, so this is a regression).

**Comment by camfindlay** [comment]
This was a conscious decision that was made during the docs rework. It's actually to do with docsviewer rather than this project per say. We followed how Laravell docs (at the time though this has now changed) do their switch of versions. We would have to consider the change in docs structure made partway between 3.1 and that 3.0 and 2.4 have a completely different structure to 3.1+ - if we can address those issues then I agree it would be useful to re-introduce that feature to docs.

**Comment by chillu** [comment]
Different structures in legacy versions of SilverStripe aren't very relevant any more, right? And I'd rather take the odd chance that somebody hits a path which doesn't exist in another version, rather than virtually every user having a bad experience when they switch between versions.

**Comment by dhensby** [comment]
This is all really related to how we redirect users and the discussions around 301s. I think this is important, though.

What I think is more annoying would be seeing the docks for 2.x and wanting to find the equivelent for 3 and finding it 404s

**Comment by camfindlay** [comment]
Agree, important. Both dealing with 301s and if we can get that cleaned up it would open the way to implementing this feature.

**Comment by SpiritLevel** [comment]
And the plot thickens!

**Comment by unclecheese** [comment]
The new docs site does this. If the path has no version counterpart, it goes to the home page.
