### ISSUE TITLE
Auto-redirect changelogs/* and contributing/* to latest master release

### ISSUE THREAD

**Issue by chillu** [silverstripe/doc.silverstripe.org#121]
Documents in these folders aren't meant to be viewed in older versions - their information isn't tied to SilverStripe releases. It's actually damaging to the way we share information to point these to older releases. For example, the RFC process isn't documented in the 3.1 release line. And none of the 3.2 changelogs will exist on the 3.1 release line. Sorry to sound like a broken record, but this also used to work about a year ago ;)

**Comment by camfindlay** [comment]
Older releases do include a big warning box stating they aren't stable and info should be taken from the stable version. Still understand your point here. 

Perhaps we can redirect up if a version if less than current stable (and down for dev versions), direct to current stable docs for those particular sections? 

Most of the docs in a given version get merged into what ever the stable branch version is in github (3.2 at time of writing) and merge ups to master don't happen all that regular. 

This might sort that out so that at any given time the latest stable contains the truth for those sections. It was weird bouncing people around versions when they navigated to certain sections of the current stable docs. If stable is /en/3.2/ I'd like to keep them in that context while also giving them the best information.

**Comment by chillu** [comment]
> Older releases do include a big warning box stating they aren't stable and info should be taken from the stable version.

This isn't about stable vs. old versions, it's behaviour specifically for those two paths - they're "timeless" so to speak, not tied to a release. So if you add a paragraph e.g. at https://docs.silverstripe.org/en/4.0/contributing/issues_and_bugs/, I'd expect this to happen on master since the process applies to all releases. This is particularly important since, as you say, stable -> master merges don't happen that often.

I see your point about bouncing people around. Maybe we limit the auto-redirect to changelogs, and make it clear on https://docs.silverstripe.org/en/3.2/contributing/documentation/ that non-release-specific docs are expected to go on the latest stable branch? changelogs could still require a redirect IMHO, since we won't merge "down" from 4.x to 3.x - and ideally you have one place of truth for all changelogs regarless of release status, right?

**Comment by camfindlay** [comment]
Perhaps some sort of non-versioned content exception in docs viewer might be a better approach?

**Comment by dhensby** [comment]
Yes, we need some way of having non-versioned docs

**Comment by camfindlay** [comment]
Could be a feature for docs viewer where you can define a path not to be versioned (and supply the version that should always be shown under the hood).

**Comment by dhensby** [comment]
yep

**Comment by camfindlay** [comment]
hackday @dhensby ? ;)

**Comment by dhensby** [comment]
I've got a lot to do on hack days ;)

**Comment by camfindlay** [comment]
don't we all :shipit:  ;)

**Comment by chillu** [comment]
@dhensby @camfindlay Sent a PR with https://github.com/silverstripe/doc.silverstripe.org/pull/137 for this.
